spot#handleFile(bytes32 ilk, bytes32 what, uint256 data)
protofire/maker-protocol-subgraph pull request #26
Opened 2022-05-05 11:31 UTC by NMohm

Implement Test for spot#handleFile

2022-05-05 11:32 UTC, NMohm commented
This PR is ready. But please merge after #24 since I included the changes here for easier testing.

2022-05-16 15:41 UTC, llopez requested changes
I looks good. Just one variable name change in favor of legibility

2022-05-16 15:41 UTC, llopez commented on src/mappings/modules/core/spot.ts
> +    let collateral = CollateralType.load(ilk)
more representative variable name. maybe `collateralType`

2022-05-16 16:49 UTC, llopez approved these changes

2022-05-16 16:50 UTC, merged