pot/drip mapping + test
protofire/maker-protocol-subgraph pull request #68
Opened 2022-06-25 10:56 UTC by ptPierre

2022-06-27 19:17 UTC, llopez requested changes

2022-06-27 19:17 UTC, llopez commented on tests/mappings/modules/rates/pot/handleDrip.test.ts
> +
please check `lastDripCall` is updated

2022-06-27 19:17 UTC, llopez commented on src/mappings/modules/rates/pot.ts
> +  system.rateAccumulator = callResult.value
I guess we need to update the value of `ratesAccumulator` with the result of `tmp = rmul(rpow(dsr, now - rho, ONE), chi);`

2022-06-27 19:17 UTC, llopez commented on subgraph.yaml
> +        # function drip(uint tab)
no parameters here

2022-06-27 20:47 UTC, rtomas commented on schema.graphql
> +
I suggest adding the name of the contract to the description and to the var name. There is another drip in the Jug contract.

2022-07-07 20:01 UTC, llopez approved these changes

2022-07-07 20:14 UTC, merged