Feature/dog/digs
protofire/maker-protocol-subgraph pull request #69
Opened 2022-06-27 11:13 UTC by ptPierre

2022-06-27 19:54 UTC, llopez requested changes

2022-06-27 19:54 UTC, llopez commented on schema.graphql
> +  totalAuctionDebtAndFees: BigDecimal!
maybe `totalDaiAmountToCoverDebtAndFees`? what do you think?

2022-06-27 19:54 UTC, llopez commented on schema.graphql
> +  dirt: BigDecimal!
improve naming, maybe: `daiAmountToCoverDebtAndFees`

2022-06-27 19:54 UTC, llopez commented on src/mappings/modules/liquidation/dog.ts
> +  let collType = collateralTypes.loadOrCreateCollateralType(event.params.ilk.toString())
variable name to `collateralType`

2022-06-27 21:10 UTC, rtomas commented on tests/mappings/modules/liquidation/dog/handleDigs.test.ts
> +    assert.fieldEquals('CollateralType', 'ETH-A', 'dirt', '-10000')
Do you think is a good idea to add to the entity systemState in the field totalAuctionDebtAndFees = 0 and save it ?

2022-06-28 15:44 UTC, llopez commented on tests/mappings/modules/liquidation/dog/handleDigs.test.ts
> +    let ilk = Bytes.fromHexString("4554482D41000000000000000000000000000000000000000000000000000000")
this is a little hard to read for humans. maybe plain string value?

2022-07-01 18:58 UTC, llopez approved these changes

2022-07-01 18:59 UTC, merged