Feature/dog#handle file
protofire/maker-protocol-subgraph pull request #71
Opened 2022-06-28 14:01 UTC by NMohm

2022-06-28 20:54 UTC, rtomas requested changes

2022-06-28 20:54 UTC, rtomas commented on schema.graphql
> +  maxDaiCoverForAuction: BigDecimal!
Maybe a better name is maxDaiToCoverAuction

2022-06-29 15:37 UTC, llopez approved these changes
looks good. I just suggested a better field name

2022-06-29 15:37 UTC, llopez commented on schema.graphql
> +  maxDaiCoverForAuction: BigDecimal!
`maxDaiToCoverAuction` maybe

2022-06-29 18:21 UTC, llopez approved these changes

2022-06-29 18:22 UTC, merged